
    - name: Upload Finished Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Z8803BE-Clean-ThreeUK-Firmware
        path: openwrt-source/bin/targets/mediatek/filogic/*sysupgrade.bin
