name: OpenWrt 25.12 ZBT-Z8803BE Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download and Extract OpenWrt Image Builder
      run: |
        wget https://openwrt.org
        tar -xf openwrt-imagebuilder-25.12.2-mediatek-filogic.Linux-x86_64.tar.zst
        mv openwrt-imagebuilder-25.12.2-mediatek-filogic.Linux-x86_64 imagebuilder

    - name: Patch Image Builder to Include Missing Device Profiles
      run: |
        cd imagebuilder
        sed -i 's/zbtlink_zbt-z8103ax-c/zbtlink_zbt-z8803be zbtlink_zbt-z8103ax-c/g' target/linux/mediatek/image/filogic.mk || true

    - name: Compile Unlocked Custom Firmware Image
      run: |
        cd imagebuilder
        make image PROFILE=zbtlink_zbt-z8803be PACKAGES="luci kmod-usb-net-rndis kmod-usb-net-cdc-ether kmod-usb-net-cdc-ncm kmod-usb-wdm kmod-usb-serial kmod-usb-serial-option kmod-usb-serial-wwan -kmod-vrf -kmod-bonding -luci-app-vrf"

    - name: Upload Clean Recovery Firmware
      uses: actions/upload-artifact@v4
      with:
        name: Clean_ZBT_Z8803BE_Image
        path: imagebuilder/bin/targets/mediatek/filogic/*sysupgrade.bin
